package chats.cash.chats_field.network.response

data class VendorOnboardingResponse(
    val RoleId: Int,
    val Store: Store,
    val address: String,
    val bvn: Any,
    val createdAt: String,
    val dob: Any,
    val email: String,
    val first_name: String,
    val gender: Any,
    val id: Int,
    val is_bvn_verified: Boolean,
    val is_email_verified: Boolean,
    val is_nin_verified: Boolean,
    val is_phone_verified: Boolean,
    val is_public: Boolean,
    val is_self_signup: Boolean,
    val is_tfa_enabled: Boolean,
    val last_login: Any,
    val last_name: String,
    val location: String,
    val marital_status: Any,
    val nfc: Any,
    val nin: Any,
    val phone: String,
    val pin: Any,
    val profile_pic: Any,
    val referal_id: Any,
    val status: String,
    val updatedAt: String,
    val vendor_id: String
)